os: linux
dist: focal
language: python
python:
    - "3.7"
before_install:
    - sudo apt-get -y install libreoffice
    - sudo ln -sf /usr/libreoffice6.4/program/python /tmp/python
install:
    - pip install pytest
script:
    - make info
    - make test
