os: linux
dist: xenial
language: python
python:
    - "3.7"
before_install:
    - sudo bash ci/linux.bash
install:
    - pip install pytest flake8 pyflakes pycodestyle autopep8 graphviz
script:
    - make all
